extra-keys = [['ESC','/','-',{key:'HOME',display:'⌂'},{key:'UP',display:'▲'},{key:'END',display:'⤓'}],['TAB','CTRL','ALT',{key:'LEFT',display:'◀'},{key:'DOWN',display:'▼'},{key:'RIGHT',display:'▶'}]]
